export type SelectorName =
  | 'Recipe Name'
  | 'Headline'
  | 'Allergens'
  | 'Description'
  | 'Nutrition per 100g button active'
  | 'Nutrition per 100g button'
  | 'Shipped Ingredients'
  | 'Not Shipped Ingredients'
  | 'Instructions'
  | 'Recipe Metrics'
  | 'Nutrition Step'
  | 'Recipe PDF'
  | 'Utensils List Item'